version: "3"
services:
  go-http-test:
    container_name: "go-http-test"
    image: golang:1.18-alpine3.16
    working_dir: /usr/src/app
    command: sh run.sh
    environment:
      - GOPROXY=https://goproxy.io
    volumes:
      - ./go-http:/usr/src/app
    expose:
      - "3011"
    ports:
      - "3011:3011"
    networks:
      app_net:
        ipv4_address: 10.10.10.11
  node-http-test:
    container_name: "node-http-test"
    image: node:16-alpine3.16
    working_dir: /home/node/app
    command: sh run.sh
    volumes:
      - ./node-http:/home/node/app
    expose:
      - "3033"
    ports:
      - "3033:3033"
    networks:
      app_net:
        ipv4_address: 10.10.10.33
networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
